[package]
name = "mouse_maze"
version = "0.1.0"
edition = "2024"

[dependencies]
avian2d = "0.3.1"
bevy = "0.16.1"
bevy_ecs_tilemap = "0.16.0"
knossos = "1.2.0"
rand = "0.9.2"
serde = "1.0.226"
serde_json = "1.0.145"
